{% set name = "Semi-ATE-STDF" %}
{% set version = "0.1.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STDF-{{ version }}.tar.gz
  sha256: 3197e69ae6d6b54ae259f43d7e6ae1a836a5c66add801982669d06c2abee0b09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - Semi_ATE.STDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE-STDF/
  summary: Library to read/write STDF/ATDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
