{% set name = "Semi-ATE-STDF" %}
{% set version = "0.1.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STDF-{{ version }}.tar.gz
  sha256: 2303a983ff608d9b7f16fd75c4a9db171625ea188df074a5a4d5b655d5467b3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - Semi_ATE.STDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE-STDF/
  summary: Library to read/write STDF/ATDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
