{% set name = "Semi-ATE-STDF" %}
{% set version = "0.1.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STDF-{{ version }}.tar.gz
  sha256: 0ce5999e5591f8ff271c944c2f0b47d8e3a45d3d04f26963c0fc6b6b14ab73e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - Semi_ATE.STDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE-STDF/
  summary: Library to read/write STDF/ATDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
