{% set name = "Semi-ATE-STDF" %}
{% set version = "0.1.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STDF-{{ version }}.tar.gz
  sha256: 1282d85c85bd89f99a00d95445335729f9098e25567a36da85e085e76d93775b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - pyqt
    - xlsxwriter

  run:
    - python >=3.7
    - pyqt
    - xlsxwriter

test:
  imports:
    - Semi_ATE.STDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE-STDF/
  summary: Library to read/write STDF/ATDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
