{% set name = "Semi-ATE-STDF" %}
{% set version = "0.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STDF-{{ version }}.tar.gz
  sha256: a9ec43c0a5e30fb6c6f274fafd6eebfde37c9f34e0b16c19d6659bd9b4ba9f75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - Semi_ATE.STDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Semi-ATE-STDF/
  summary: Library to read/write STDF/ATDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
